### ISSUE TITLE
Use java client from Maven once it's released

### ISSUE THREAD

**Issue by tirkarthi** [vedang/clj_fdb#1]
At some point FoundationDB java client will be released in Maven so that you can include it as a dependency in project.clj instead of manual installation. I am opening this is a reminder. Feel free to close this if you have other approaches.

Upstream issue : https://github.com/apple/foundationdb/issues/219

Thanks

**Comment by vedang** [comment]
Thanks! Will keep this open until the upstream issue is fixed and I can push to clojars!
