### ISSUE TITLE
Use API version 520 in examples and docs

### ISSUE THREAD

**Issue by tirkarthi** [vedang/clj_fdb#23]
**Describe the bug**

API version 520 is the used in the updated docs and hence examples could be updated. The travis build is already fixed with latest deb files and corresponding compatible fdb java library.

**Comment by vedang** [comment]
Thanks for this, I'll update all the docs/examples over the weekend

**Comment by vedang** [comment]
I've updated all the docs/examples to use version `600`, which is the latest version. Closing this issue.
