### ISSUE TITLE
Use GH pages and codox for docs

### ISSUE THREAD

**Issue by tirkarthi** [vedang/clj_fdb#4]
GitHub allows hosting project docs in your GitHub pages domain with docs folder in master or gh-pages. This has to be enabled in project settings which I don't have access to. You can use codox plugin to generate docs from the source. This also hyperlinks the source code with the docs and so on that will be useful. One disadvantage is that using docs folder in master helps in maintaining it easily but might pollute the master branch history.

Sample config : https://github.com/tirkarthi/clj-foundationdb/blob/723b315076da4e06315eed93d505d5f5dbff3085/project.clj#L13

Sample docs : https://tirkarthi.github.io/clj-foundationdb

GitHub pages for docs : https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

Let me know if you would like a PR to master with config and docs generated.

**Comment by vedang** [comment]
Thanks for the suggestion and the links. I've created codox documentation in the `gh-pages` branch for this project!
